apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    app: development-ns


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: development
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: paulbouwer/hello-kubernetes:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

