name: "Create Kubernetes Resources"

on: workflow_dispatch

jobs:
  resources:
    name: "Deploy Resource"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:	
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETE_ID }}
          aws-region: 'eu-west-1'

      - name: Resource Setup
        uses: azure/setup-kubectl@v2.0
        id: install
        with:
          version: 'v1.21.3'

      - name: Update kube config
        run: aws eks update-kubeconfig --name abn-amro --region eu-west-1

      - name: Create Hello App
        id: create
        run: |
          cd resources
          kubectl apply -f app.yaml
